cisco-en-programmability/catalystwan-sdk

- catalystwan/api/templates/models/aaa_model.py
- catalystwan/api/templates/models/cisco_aaa_model.py
- catalystwan/api/templates/models/cisco_system.py
- catalystwan/api/templates/models/cisco_vpn_model.py
- catalystwan/api/templates/models/system_vsmart_model.py
- catalystwan/api/templates/models/vpn_vsmart_interface_model.py
- catalystwan/endpoints/configuration/software_actions.py
- catalystwan/endpoints/configuration_dashboard_status.py
- catalystwan/models/common.py
- catalystwan/models/configuration/feature_profile/common.py
- catalystwan/models/configuration/feature_profile/sdwan/application_priority/traffic_policy.py
- catalystwan/models/configuration/feature_profile/sdwan/policy_object/security/ssl_decryption.py
- catalystwan/models/configuration/feature_profile/sdwan/policy_object/security/ssl_decryption_profile.py
- catalystwan/models/configuration/feature_profile/sdwan/service/lan/ethernet.py
- catalystwan/models/configuration/feature_profile/sdwan/system/logging_parcel.py
- catalystwan/models/configuration/feature_profile/sdwan/topology/custom_control.py
- catalystwan/models/policy/definition/url_filtering.py
- catalystwan/models/policy/list/identity.py
- catalystwan/tests/templates/test_serialize_model.py
- pyproject.toml
- fix fields serialization
- fix multiple mypy validation errors
Fix type in field serialization and validation
> dev: Fix ethernet serialization

- catalystwan/models/configuration/feature_profile/sdwan/service/lan/ethernet.py
Fix field name
[Add more in depth analysis of what changed, provide logs, examples of usage]
> Fix ethernet field name

- catalystwan/models/configuration/feature_profile/sdwan/service/lan/ethernet.py
- pyproject.toml
Every version has snake case in group_id
[Add more in depth analysis of what changed, provide logs, examples of usage]
> Fix/ethernet vrrp | Every version has snake case in group_id

- pyproject.toml
[Describe briefly what the PR is about]
[Add more in depth analysis of what changed, provide logs, examples of usage]
> dev: bump 0.40.0dev6

- catalystwan/models/configuration/feature_profile/sdwan/service/lan/vpn.py
- pyproject.toml
> fix typo and bump to dev8

- catalystwan/models/configuration/feature_profile/sdwan/embedded_security/policy.py
- catalystwan/models/policy/security.py
Update security policy models after validation failure is found using data from field.
> dev: fix security policy model

- catalystwan/models/configuration/feature_profile/sdwan/service/lan/vpn.py
- add missing field to a model
> dev: Fix omp advertise ipv6

- ENDPOINTS.md
- pyproject.toml
> release-v0.40.1.dev7

- catalystwan/models/policy/list/supervisory_disconnect.py
- catalystwan/models/policy/policy_definition.py
- catalystwan/models/policy/voice.py
Fix `uc-voice` configuration item models
> dev: fix uc voice models

- pyproject.toml
> dev: Bump 0.40.1dev8

- pyproject.toml
> Dev bump 0.40.1dev10

- pyproject.toml
> Dev: bump 0.40.1dev14

- ENDPOINTS.md
- pyproject.toml
> release-v0.40.2

- catalystwan/apigw_auth.py
Print reponse content after http error
> dev: Api gw print response content

- README.md
updated example for export csv of device templates in README
updated example for export csv of device templates in README
> updated example for export csv in README

- ENDPOINTS.md
- catalystwan/apigw_auth.py
- pyproject.toml
- Allow user to override default 10s timeout for apigw `/login` request
- bump version: `0.40.2dev3`
> dev: parametrized apigw auth request timeout

- ENDPOINTS.md
- catalystwan/integration_tests/profile_builder/test_pb_uc_voice.py
- catalystwan/models/configuration/feature_profile/sdwan/uc_voice/digital_interface.py
- pyproject.toml
- fix cableLength enum for digital voicecard
- bump version `0.40.2dev5`
> dev: fix dig voice card

- ENDPOINTS.md
- catalystwan/models/common.py
- catalystwan/models/configuration/feature_profile/sdwan/uc_voice/digital_interface.py
- catalystwan/models/configuration/feature_profile/sdwan/uc_voice/media_profile.py
- catalystwan/models/policy/list/media_profile.py
- pyproject.toml
- fix media profile models
- fix digital interface validator
- release `v0.40.2dev6`
> dev: fix media profile models

- ENDPOINTS.md
- catalystwan/models/common.py
- catalystwan/models/configuration/feature_profile/sdwan/uc_voice/supervisory_disconnect.py
- catalystwan/models/policy/list/supervisory_disconnect.py
- pyproject.toml
- improve supervisory disc model
- bump version `v0.40.2dev7`
> dev: improve supervisory disc model

- catalystwan/models/configuration/feature_profile/sdwan/system/aaa.py
Use `populate_by_name` in `PubkeyChainItem`
> Dev: Fix aaa pubkey

- pyproject.toml
> dev: Bump 0.40.2dev9

- ENDPOINTS.md
- catalystwan/models/configuration/feature_profile/sdwan/uc_voice/digital_interface.py
- pyproject.toml
> release-v0.40.2.dev10

- ENDPOINTS.md
- catalystwan/apigw_auth.py
- catalystwan/response.py
- catalystwan/session.py
- pyproject.toml
- apigw handling improvements
- release `0.41.0`
> Release v0.41.0

- catalystwan/api/template_api.py
This PR allow Template API to edit CLI templates
> Edit CLI templates

- pyproject.toml
> [dev] bump 0.41.0dev1

- ENDPOINTS.md
- catalystwan/models/configuration/network_hierarchy/node.py
- pyproject.toml
- fix: network hierarchy node gps location fields
- bump dev version to `0.41.0.dev4`
> dev: fix network hierarchy node gps location

- catalystwan/models/configuration/feature_profile/sdwan/system/basic.py
change field `description` to `device_description` to avoid serialization problems
> [dev] basic parcel - change field name

- catalystwan/models/policy/policy_list.py
add references field model for policy list info
> [dev] policy list references model

- ENDPOINTS.md
- catalystwan/models/configuration/feature_profile/sdwan/application_priority/traffic_policy.py
- pyproject.toml
- add data traffic cloud probe action setter
- bump dev version to: `0.41.0.dev7`
> [dev] add data traffic cloud probe action setter

- catalystwan/models/configuration/feature_profile/sdwan/service/lan/svi.py
[Describe briefly what the PR is about]
[Add more in depth analysis of what changed, provide logs, examples of usage]
> [dev] vrrp: change serialization to algin with schema

- catalystwan/models/configuration/feature_profile/sdwan/topology/custom_control.py
Allow empty list for `inbound_sites` and `outbound_sites` in custom control
> [dev] allow empty target sites
